=begin
#nlpapi

#The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::ExtractEntitiesStringApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExtractEntitiesStringApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::ExtractEntitiesStringApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExtractEntitiesStringApi' do
    it 'should create an instance of ExtractEntitiesStringApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::ExtractEntitiesStringApi)
    end
  end

  # unit tests for extract_entities_string_post
  # Extract entities from string
  # Extract the named entitites from an input string.
  # @param value Input string
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'extract_entities_string_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
