=begin
#nlpapiv2

#The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::LanguageTranslationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LanguageTranslationApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::LanguageTranslationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LanguageTranslationApi' do
    it 'should create an instance of LanguageTranslationApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::LanguageTranslationApi)
    end
  end

  # unit tests for language_translation_translate_deu_to_eng
  # Translate German to English text with Deep Learning AI
  # Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_deu_to_eng test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for language_translation_translate_eng_to_deu
  # Translate English to German text with Deep Learning AI
  # Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_eng_to_deu test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for language_translation_translate_eng_to_fra
  # Translate English to French text with Deep Learning AI
  # Automatically translates input text in English to output text in French using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_eng_to_fra test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for language_translation_translate_eng_to_rus
  # Translate English to Russian text with Deep Learning AI
  # Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_eng_to_rus test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for language_translation_translate_fra_to_eng
  # Translate French to English text with Deep Learning AI
  # Automatically translates input text in French to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_fra_to_eng test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for language_translation_translate_rus_to_eng
  # Translate Russian to English text with Deep Learning AI
  # Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
  # @param input Input translation request
  # @param [Hash] opts the optional parameters
  # @return [LanguageTranslationResponse]
  describe 'language_translation_translate_rus_to_eng test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
