=begin
#nlpapiv2

#The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::LanguageDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LanguageDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::LanguageDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LanguageDetectionApi' do
    it 'should create an instance of LanguageDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::LanguageDetectionApi)
    end
  end

  # unit tests for language_detection_get_language
  # Detect language of text
  # Automatically determine which language a text string is written in.  Supports Danish (DAN), German (DEU), English (ENG), French (FRA), Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE), Chinese (ZHO).
  # @param input 
  # @param [Hash] opts the optional parameters
  # @return [LanguageDetectionResponse]
  describe 'language_detection_get_language test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
