=begin
#nlpapi

#The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::ParseStringApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ParseStringApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::ParseStringApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ParseStringApi' do
    it 'should create an instance of ParseStringApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::ParseStringApi)
    end
  end

  # unit tests for parse_string_post
  # Parse string to syntax tree
  # Parses the input string into a Penn Treebank syntax tree
  # @param input Input string
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'parse_string_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
