=begin
#nlpapi

#The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::PosTaggerStringApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PosTaggerStringApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::PosTaggerStringApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PosTaggerStringApi' do
    it 'should create an instance of PosTaggerStringApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::PosTaggerStringApi)
    end
  end

  # unit tests for pos_tagger_string_post
  # Part-of-speech tag a string
  # Perform a part-of-speech (POS) tagging on the input string.
  # @param input Input string
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'pos_tagger_string_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
