=begin
#nlpapiv2

#The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::RephraseApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RephraseApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::RephraseApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RephraseApi' do
    it 'should create an instance of RephraseApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::RephraseApi)
    end
  end

  # unit tests for rephrase_translate_deu_to_eng
  # Rephrase, paraphrase English text sentence-by-sentence using Deep Learning AI
  # Automatically rephrases or paraphrases input text in English sentence by sentence using advanced Deep Learning and Neural NLP.  Creates multiple reprhasing candidates per input sentence, from 1 to 10 possible rephrasings of the original sentence.  Seeks to preserve original semantic meaning in rephrased output candidates.  Consumes 1-2 API calls per output rephrasing option generated, per sentence.
  # @param input Input rephrase request
  # @param [Hash] opts the optional parameters
  # @return [RephraseResponse]
  describe 'rephrase_translate_deu_to_eng test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
