=begin
#nlpapi

#The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::SentencesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SentencesApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::SentencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SentencesApi' do
    it 'should create an instance of SentencesApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::SentencesApi)
    end
  end

  # unit tests for sentences_post
  # Extract sentences from string
  # Segment an input string into separate sentences, output result as a string.
  # @param input Input string
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'sentences_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
