=begin
#nlpapiv2

#The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveNlpApiClient::SpellcheckApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpellcheckApi' do
  before do
    # run before each test
    @instance = CloudmersiveNlpApiClient::SpellcheckApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpellcheckApi' do
    it 'should create an instance of SpellcheckApi' do
      expect(@instance).to be_instance_of(CloudmersiveNlpApiClient::SpellcheckApi)
    end
  end

  # unit tests for spellcheck_check_sentence
  # Check if sentence is spelled correctly
  # Checks whether the sentence is spelled correctly and returns the result as JSON
  # @param value Input sentence
  # @param [Hash] opts the optional parameters
  # @return [CheckSentenceResponse]
  describe 'spellcheck_check_sentence test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for spellcheck_correct_json
  # Find spelling corrections
  # Find spelling correction suggestions and return result as JSON
  # @param value Input string
  # @param [Hash] opts the optional parameters
  # @return [CheckWordResponse]
  describe 'spellcheck_correct_json test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
